name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4 to use Node.js 16

      - name: Check for 'which' command existence
        run: command -v which || echo "which not found"

      - name: Check for 'git' command existence
        run: command -v git || echo "git not found"

      - name: Check for 'node' command existence
        run: command -v node || echo "node not found"

      - name: Quiz 1
        id: quiz-1
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Quiz 1
          setup-command: ''
          command: echo "Which of the following best describes software engineering?"
          input: |-
            a) The study of hardware components
            b) The process of designing, developing, and maintaining software
            c) The analysis of networking protocols
            d) The management of data storage systems
          expected-output: b) The process of designing, developing, and maintaining software
          comparison-method: exact
          timeout: 10
          max-score: 10

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          QUIZ-1_RESULTS: "${{steps.quiz-1.outputs.result}}"
        with:
          runners: quiz-1

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Autograding Tests: Added command existence checks and updated workflow" -m "This commit includes steps to check for the existence of 'which', 'git', and 'node' commands, ensuring the necessary tools are available for the autograding process. Additionally, it updates the workflow to improve reliability and maintainability."
          git push

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4 to use Node.js 16
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git nodejs
      - name: Run tests
        run: npm test
